/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VersionVersionRouteImport } from './routes/version.$version'
import { Route as DesignVersionIdRouteImport } from './routes/design.$version.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionVersionRoute = VersionVersionRouteImport.update({
  id: '/version/$version',
  path: '/version/$version',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignVersionIdRoute = DesignVersionIdRouteImport.update({
  id: '/design/$version/$id',
  path: '/design/$version/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/version/$version': typeof VersionVersionRoute
  '/design/$version/$id': typeof DesignVersionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/version/$version': typeof VersionVersionRoute
  '/design/$version/$id': typeof DesignVersionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/version/$version': typeof VersionVersionRoute
  '/design/$version/$id': typeof DesignVersionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/version/$version' | '/design/$version/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/version/$version' | '/design/$version/$id'
  id: '__root__' | '/' | '/version/$version' | '/design/$version/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VersionVersionRoute: typeof VersionVersionRoute
  DesignVersionIdRoute: typeof DesignVersionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version/$version': {
      id: '/version/$version'
      path: '/version/$version'
      fullPath: '/version/$version'
      preLoaderRoute: typeof VersionVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design/$version/$id': {
      id: '/design/$version/$id'
      path: '/design/$version/$id'
      fullPath: '/design/$version/$id'
      preLoaderRoute: typeof DesignVersionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VersionVersionRoute: VersionVersionRoute,
  DesignVersionIdRoute: DesignVersionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
